/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adivinaquien;

import java.util.*;
import javax.swing.*;

/**
 *
 * @author Marco
 */
public class Tablero extends javax.swing.JFrame {
    
    private ArrayList<JButton> buttonArray;
    private ImageIcon backIcon;
    private AdivinaQuien controlador;

    /**
     * Creates new form Tablero
     */
    public Tablero(AdivinaQuien controlador) {
        initComponents();
        this.controlador = controlador;
        Random rand = new Random();
        int i = rand.nextInt(24);
        controlador.getJugador().setPersonaje(i);
        miPersonaje.setIcon(new ImageIcon("src/adivinaquien/" + i + ".jpg"));
        buttonArray = new ArrayList<JButton>();
        backIcon = new ImageIcon("src/adivinaquien/back.jpg");
        llenaArray();
        java.awt.Dimension dim = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tu = new javax.swing.JLabel();
        oponente = new javax.swing.JLabel();
        adivinacion = new javax.swing.JLabel();
        tu_personaje = new javax.swing.JLabel();
        listaNombres = new javax.swing.JComboBox<>();
        botonPreguntar = new javax.swing.JButton();
        botonAdivina = new javax.swing.JButton();
        alex = new javax.swing.JButton();
        alfred = new javax.swing.JButton();
        anita = new javax.swing.JButton();
        anne = new javax.swing.JButton();
        bernard = new javax.swing.JButton();
        bill = new javax.swing.JButton();
        charles = new javax.swing.JButton();
        claire = new javax.swing.JButton();
        david = new javax.swing.JButton();
        eric = new javax.swing.JButton();
        frans = new javax.swing.JButton();
        george = new javax.swing.JButton();
        herman = new javax.swing.JButton();
        joe = new javax.swing.JButton();
        maria = new javax.swing.JButton();
        max = new javax.swing.JButton();
        paul = new javax.swing.JButton();
        peter = new javax.swing.JButton();
        philip = new javax.swing.JButton();
        richard = new javax.swing.JButton();
        robert = new javax.swing.JButton();
        sam = new javax.swing.JButton();
        susan = new javax.swing.JButton();
        tom = new javax.swing.JButton();
        miPersonaje = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adivina Quién");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tu.setText("Tu:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        getContentPane().add(tu, gridBagConstraints);

        oponente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oponente.setText("Oponente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        getContentPane().add(oponente, gridBagConstraints);

        adivinacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        adivinacion.setText("Adivinación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(adivinacion, gridBagConstraints);

        tu_personaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tu_personaje.setText("Tu personaje:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(tu_personaje, gridBagConstraints);

        listaNombres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alex", "Alfred", "Anita", "Anne", "Bernard", "Bill", "Charles", "Claire", "David", "Eric", "Frans", "George", "Herman", "Joe", "Maria", "Max", "Paul", "Peter", "Philip", "Richard", "Robert", "Sam", "Susan", "Tom" }));
        listaNombres.setPreferredSize(new java.awt.Dimension(90, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(listaNombres, gridBagConstraints);

        botonPreguntar.setText("Preguntar");
        botonPreguntar.setFocusPainted(false);
        botonPreguntar.setPreferredSize(new java.awt.Dimension(120, 22));
        botonPreguntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPreguntarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 8;
        getContentPane().add(botonPreguntar, gridBagConstraints);

        botonAdivina.setText("Adivina");
        botonAdivina.setFocusPainted(false);
        botonAdivina.setPreferredSize(new java.awt.Dimension(67, 25));
        botonAdivina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdivinaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(botonAdivina, gridBagConstraints);

        alex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/0.jpg"))); // NOI18N
        alex.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        alex.setFocusPainted(false);
        alex.setPreferredSize(new java.awt.Dimension(70, 120));
        alex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        getContentPane().add(alex, gridBagConstraints);

        alfred.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/1.jpg"))); // NOI18N
        alfred.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        alfred.setFocusPainted(false);
        alfred.setPreferredSize(new java.awt.Dimension(70, 120));
        alfred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        getContentPane().add(alfred, gridBagConstraints);

        anita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/2.jpg"))); // NOI18N
        anita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        anita.setFocusPainted(false);
        anita.setPreferredSize(new java.awt.Dimension(70, 120));
        anita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        getContentPane().add(anita, gridBagConstraints);

        anne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/3.jpg"))); // NOI18N
        anne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        anne.setFocusPainted(false);
        anne.setPreferredSize(new java.awt.Dimension(70, 120));
        anne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        getContentPane().add(anne, gridBagConstraints);

        bernard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/4.jpg"))); // NOI18N
        bernard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bernard.setFocusPainted(false);
        bernard.setPreferredSize(new java.awt.Dimension(70, 120));
        bernard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 1;
        getContentPane().add(bernard, gridBagConstraints);

        bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/5.jpg"))); // NOI18N
        bill.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bill.setFocusPainted(false);
        bill.setPreferredSize(new java.awt.Dimension(70, 120));
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 1;
        getContentPane().add(bill, gridBagConstraints);

        charles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/6.jpg"))); // NOI18N
        charles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        charles.setFocusPainted(false);
        charles.setPreferredSize(new java.awt.Dimension(70, 120));
        charles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 1;
        getContentPane().add(charles, gridBagConstraints);

        claire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/7.jpg"))); // NOI18N
        claire.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        claire.setFocusPainted(false);
        claire.setPreferredSize(new java.awt.Dimension(70, 120));
        claire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 1;
        getContentPane().add(claire, gridBagConstraints);

        david.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/8.jpg"))); // NOI18N
        david.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        david.setFocusPainted(false);
        david.setPreferredSize(new java.awt.Dimension(70, 120));
        david.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        getContentPane().add(david, gridBagConstraints);

        eric.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/9.jpg"))); // NOI18N
        eric.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eric.setFocusPainted(false);
        eric.setPreferredSize(new java.awt.Dimension(70, 120));
        eric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        getContentPane().add(eric, gridBagConstraints);

        frans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/10.jpg"))); // NOI18N
        frans.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        frans.setFocusPainted(false);
        frans.setPreferredSize(new java.awt.Dimension(70, 120));
        frans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        getContentPane().add(frans, gridBagConstraints);

        george.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/11.jpg"))); // NOI18N
        george.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        george.setFocusPainted(false);
        george.setPreferredSize(new java.awt.Dimension(70, 120));
        george.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 3;
        getContentPane().add(george, gridBagConstraints);

        herman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/12.jpg"))); // NOI18N
        herman.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        herman.setFocusPainted(false);
        herman.setPreferredSize(new java.awt.Dimension(70, 120));
        herman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 3;
        getContentPane().add(herman, gridBagConstraints);

        joe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/13.jpg"))); // NOI18N
        joe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        joe.setFocusPainted(false);
        joe.setPreferredSize(new java.awt.Dimension(70, 120));
        joe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 3;
        getContentPane().add(joe, gridBagConstraints);

        maria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/14.jpg"))); // NOI18N
        maria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        maria.setFocusPainted(false);
        maria.setPreferredSize(new java.awt.Dimension(70, 120));
        maria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 3;
        getContentPane().add(maria, gridBagConstraints);

        max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/15.jpg"))); // NOI18N
        max.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        max.setFocusPainted(false);
        max.setPreferredSize(new java.awt.Dimension(70, 120));
        max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 3;
        getContentPane().add(max, gridBagConstraints);

        paul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/16.jpg"))); // NOI18N
        paul.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paul.setFocusPainted(false);
        paul.setPreferredSize(new java.awt.Dimension(70, 120));
        paul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        getContentPane().add(paul, gridBagConstraints);

        peter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/17.jpg"))); // NOI18N
        peter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        peter.setFocusPainted(false);
        peter.setPreferredSize(new java.awt.Dimension(70, 120));
        peter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        getContentPane().add(peter, gridBagConstraints);

        philip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/18.jpg"))); // NOI18N
        philip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        philip.setFocusPainted(false);
        philip.setPreferredSize(new java.awt.Dimension(70, 120));
        philip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        getContentPane().add(philip, gridBagConstraints);

        richard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/19.jpg"))); // NOI18N
        richard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        richard.setFocusPainted(false);
        richard.setPreferredSize(new java.awt.Dimension(70, 120));
        richard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 5;
        getContentPane().add(richard, gridBagConstraints);

        robert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/20.jpg"))); // NOI18N
        robert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        robert.setFocusPainted(false);
        robert.setPreferredSize(new java.awt.Dimension(70, 120));
        robert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 5;
        getContentPane().add(robert, gridBagConstraints);

        sam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/21.jpg"))); // NOI18N
        sam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sam.setFocusPainted(false);
        sam.setPreferredSize(new java.awt.Dimension(70, 120));
        sam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 5;
        getContentPane().add(sam, gridBagConstraints);

        susan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/22.jpg"))); // NOI18N
        susan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        susan.setFocusPainted(false);
        susan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 5;
        getContentPane().add(susan, gridBagConstraints);

        tom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adivinaquien/23.jpg"))); // NOI18N
        tom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tom.setFocusPainted(false);
        tom.setPreferredSize(new java.awt.Dimension(70, 120));
        tom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 5;
        getContentPane().add(tom, gridBagConstraints);

        miPersonaje.setBorder(null);
        miPersonaje.setFocusPainted(false);
        miPersonaje.setPreferredSize(new java.awt.Dimension(70, 120));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 4;
        getContentPane().add(miPersonaje, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 17;
        getContentPane().add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 17;
        getContentPane().add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 15;
        getContentPane().add(filler4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 15;
        getContentPane().add(filler5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        getContentPane().add(filler12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 12;
        getContentPane().add(filler13, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 15;
        getContentPane().add(filler14, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 15;
        getContentPane().add(filler15, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 15;
        getContentPane().add(filler16, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 17;
        getContentPane().add(filler17, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 17;
        getContentPane().add(filler18, gridBagConstraints);

        jTextField1.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 8;
        getContentPane().add(jTextField1, gridBagConstraints);

        jTextField2.setEditable(false);
        jTextField2.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 8;
        getContentPane().add(jTextField2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPressed
        JButton button = (JButton)evt.getSource();
        if (button.getIcon().equals(backIcon)) button.setIcon(new ImageIcon("src/adivinaquien/" + buttonArray.indexOf(button) + ".jpg"));
        else button.setIcon(backIcon);
    }//GEN-LAST:event_buttonPressed

    private void botonPreguntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPreguntarActionPerformed
        if (jTextField1.getText().isEmpty()) {
            jTextField2.setText("Escribe algo para enviar.");
            return;
        }
        if (jTextField1.getText().startsWith("Adivina: ")) {
            jTextField2.setText("Tu mensaje no puede empezar con \"Adivina: \"");
            return;
        }
        if (jTextField1.getText().startsWith("Regresa: ")) {
            jTextField2.setText("Tu mensaje no puede empezar con \"Regresa: \"");
            return;
        }
        controlador.enviar(jTextField1.getText(), botonPreguntar, botonAdivina);
    }//GEN-LAST:event_botonPreguntarActionPerformed

    private void botonAdivinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdivinaActionPerformed
        setEnabled(false);
        controlador.adivinaOnline(listaNombres.getSelectedIndex());
    }//GEN-LAST:event_botonAdivinaActionPerformed
    
    public JButton getBotonPreguntar() {
        return botonPreguntar;
    }
    
    public JButton getBotonAdivina() {
        return botonAdivina;
    }
    
    public JTextField getJTextField2() {
        return jTextField2;
    }
    
    public ArrayList<JButton> getButtonArray() {
        return buttonArray;
    }
    
    public void llenaArray() {
        buttonArray.add(alex);
        buttonArray.add(alfred);
        buttonArray.add(anita);
        buttonArray.add(anne);
        buttonArray.add(bernard);
        buttonArray.add(bill);
        buttonArray.add(charles);
        buttonArray.add(claire);
        buttonArray.add(david);
        buttonArray.add(eric);
        buttonArray.add(frans);
        buttonArray.add(george);
        buttonArray.add(herman);
        buttonArray.add(joe);
        buttonArray.add(maria);
        buttonArray.add(max);
        buttonArray.add(paul);
        buttonArray.add(peter);
        buttonArray.add(philip);
        buttonArray.add(richard);
        buttonArray.add(robert);
        buttonArray.add(sam);
        buttonArray.add(susan);
        buttonArray.add(tom);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adivinacion;
    private javax.swing.JButton alex;
    private javax.swing.JButton alfred;
    private javax.swing.JButton anita;
    private javax.swing.JButton anne;
    private javax.swing.JButton bernard;
    private javax.swing.JButton bill;
    private javax.swing.JButton botonAdivina;
    private javax.swing.JButton botonPreguntar;
    private javax.swing.JButton charles;
    private javax.swing.JButton claire;
    private javax.swing.JButton david;
    private javax.swing.JButton eric;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JButton frans;
    private javax.swing.JButton george;
    private javax.swing.JButton herman;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton joe;
    private javax.swing.JComboBox<String> listaNombres;
    private javax.swing.JButton maria;
    private javax.swing.JButton max;
    private javax.swing.JButton miPersonaje;
    private javax.swing.JLabel oponente;
    private javax.swing.JButton paul;
    private javax.swing.JButton peter;
    private javax.swing.JButton philip;
    private javax.swing.JButton richard;
    private javax.swing.JButton robert;
    private javax.swing.JButton sam;
    private javax.swing.JButton susan;
    private javax.swing.JButton tom;
    private javax.swing.JLabel tu;
    private javax.swing.JLabel tu_personaje;
    // End of variables declaration//GEN-END:variables
}
